[package]
name = "wgslsmith"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
indenter = "0.3"
indexmap = "1.7"
once_cell = "1.8"
paste = "1.0"
rand = "0.8"
rpds = "0.10"
