[package]
name = "wgslsmith"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "2.0.0-rc.1"
color-eyre = "0.6.1"
eyre = "0.6.8"
rand = "0.8"
regex = "1.5.5"
serde_json = "1.0"
tap = "1.0.1"
toml = "0.5.9"
tracing = "0.1"
wait-timeout = "0.2.0"
which = "4.2.5"

ast = { path = "../ast" }
common = { path = "../common" }
generator = { path = "../generator" }
parser = { path = "../parser" }
reconditioner = { path = "../reconditioner" }

[dependencies.clap]
version = "3.0.0"
features = ["derive"]

[dependencies.naga]
path = "../../harness/external/naga"
features = ["validate", "wgsl-in"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.time]
version = "0.3.9"
features = ["formatting", "local-offset"]

[dependencies.tracing-subscriber]
version = "0.3"
features = ["env-filter"]
