[book]
authors = ["Hasan Ali"]
language = "en"
multilingual = false
src = "src"
title = "wgslsmith"

[preprocessor]

[preprocessor.admonish]
command = "mdbook-admonish"

[output]

[output.html]
additional-css = ["././mdbook-admonish.css"]
git-repository-url = "https://github.com/wgslsmith/wgslsmith"
edit-url-template = "https://github.com/wgslsmith/wgslsmith/edit/main/docs/{path}"
