[book]
authors = ["Hasan Ali"]
language = "en"
multilingual = false
src = "src"
title = "wgslsmith"

[preprocessor]

[preprocessor.admonish]
command = "mdbook-admonish"

[output]

[output.html]
additional-css = ["././mdbook-admonish.css"]
