name: docs

on:
  push:
    paths:
      - .github/workflows/docs.yml
      - docs/**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Checkout docs repo
        uses: actions/checkout@v2
        with:
          repository: wgslsmith/wgslsmith.github.io
          path: wgslsmith.github.io
          token: ${{ secrets.GH_TOKEN }}

      - name: Install mdbook
        run: |
          curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.15/mdbook-v0.4.15-x86_64-unknown-linux-gnu.tar.gz > $HOME/mdbook.tar.gz
          sudo tar -xvf $HOME/mdbook.tar.gz -C /usr/bin

      - name: Build docs
        working-directory: docs
        run: mdbook build

      - name: Copy build output
        working-directory: wgslsmith.github.io
        run: |
          rm -rf book
          cp -r ${{ github.workspace }}/docs/book book

      - name: Setup git user details
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        working-directory: wgslsmith.github.io
        continue-on-error: true
        run: |
          git add .
          git commit -m "Publish wgslsmith/wgslsmith@${{ github.sha }}"

      - name: Publish docs
        working-directory: wgslsmith.github.io
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: git push https://github-actions[bot]:$GITHUB_TOKEN@github.com/wgslsmith/wgslsmith.github.io
