name: harness

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - crates/parser/**
      - crates/reconditioner/**
      - crates/wgslsmith/**
      - docs/**

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
        include:
          - target: x86_64-pc-windows-msvc
            os: ubuntu-20.04
            artifact: win64
            exe_suffix: .exe
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
            artifact: linux64
            exe_suffix: ""
          - target: x86_64-apple-darwin
            os: macos-11
            artifact: macos64
            exe_suffix: ""

    env:
      CARGO_BUILD_TARGET: ${{ matrix.target }}
      MACOSX_DEPLOYMENT_TARGET: "11.0"

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $HOME/depot_tools
          echo "$HOME/depot_tools" >> $GITHUB_PATH

      - name: Install dawn dependencies
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          sudo apt-get install libxrandr-dev libxinerama-dev libx11-dev libxcursor-dev libxi-dev \
            libxext-dev libxcb-shm0-dev libxtst-dev libx11-xcb-dev

      - name: Install clang
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: |
          sudo apt-get update
          sudo apt-get install clang-12 clang-tools-12 llvm-12

      - name: Install xwin
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: |
          curl -L https://github.com/Jake-Shadle/xwin/releases/download/0.2.0/xwin-0.2.0-x86_64-unknown-linux-musl.tar.gz > $HOME/xwin.tar.gz
          tar -xvf $HOME/xwin.tar.gz -C $HOME
          sudo mv $HOME/xwin-0.2.0-x86_64-unknown-linux-musl/xwin /usr/bin

      - name: Build dawn
        run: |
          ./x bootstrap
          ./x build dawn

      - name: Build harness
        run: ./x build harness -- --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: harness-${{ matrix.artifact }}
          path: target/${{ matrix.target }}/release/harness${{ matrix.exe_suffix }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Download swiftshader
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          release_tag=`gh release view --json tagName -q '.tagName' -R wgslsmith/swiftshader-build`
          gh release download $release_tag -p swiftshader-linux64.tar.gz -R wgslsmith/swiftshader-build
          tar -xf swiftshader-linux64.tar.gz

      - name: Download harness
        uses: actions/download-artifact@v3
        with:
          name: harness-linux64

      - name: Run test shaders
        env:
          VK_ICD_FILENAMES: swiftshader-linux64/vk_swiftshader_icd.json
        run: |
          chmod +x ./harness
          for i in {1..5}; do
            cat test_cases/$i.wgsl | ./harness
          done
