name: harness

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - parser/**
      - reconditioner/**
      - wgslsmith/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $HOME/depot_tools
          echo "$HOME/depot_tools" >> $GITHUB_PATH

      - run: |
          cargo xtask build-dawn
          cargo xtask build-harness
