name: harness

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - parser/**
      - reconditioner/**
      - wgslsmith/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
    env:
      MACOSX_DEPLOYMENT_TARGET: "11.0"
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $HOME/depot_tools
          echo "$HOME/depot_tools" >> $GITHUB_PATH

      - name: Install dawn dependencies
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get install libxrandr-dev libxinerama-dev libx11-dev libxcursor-dev libxi-dev \
            libxext-dev libxcb-shm0-dev libxtst-dev libx11-xcb-dev

      - name: Build dawn
        run: |
          ./x bootstrap
          ./x build dawn

      - name: Build harness
        run: ./x build harness

      # - name: Run test shaders
      #   run: |
      #     for i in {1..5}
      #     do
      #       cat test_cases/$i.wgsl | target/x86_64-unknown-linux-gnu/release/harness;
      #     done
